PSQLADM-418 2.4.3 release notes and release note tasks
percona/proxysql-admin-tool-doc pull request #55
Opened 2022-08-17 13:23 UTC by patrickbirch

Added 2.4.3.md

2022-08-17 13:24 UTC, georgelorchpercona approved these changes

2022-08-17 13:58 UTC, mohitj1988 approved these changes
Looks good

2022-08-17 14:41 UTC, alina-derkach-oaza approved these changes
LGRM

2022-08-31 10:16 UTC, venkatesh-prasad-v requested changes

2022-08-31 10:16 UTC, venkatesh-prasad-v commented on docs/2.4.3.md
> +*ProxySQL Admin* and *Percona Scheduler Admin* have not changed since the previous release.
We fixed the following two bugs for 2.4.3 release.

1. https://jira.percona.com/browse/PSQLADM-402 - Positional Parameters in proxysql-status was not working in previous releases. It has been fixed now.
2. https://jira.percona.com/browse/PSQLADM-419 - Addresses CVE-2021-38561 in pxc_scheduler_handler.

2022-08-31 10:33 UTC, patrickbirch commented on docs/2.4.3.md
> +*ProxySQL Admin* and *Percona Scheduler Admin* have not changed since the previous release.
Added.

2022-08-31 10:48 UTC, venkatesh-prasad-v approved these changes

2022-08-31 10:51 UTC, mohitj1988 approved these changes

2022-08-31 10:51 UTC, merged