PSQLADM-457 2.4.7 release notes and release note tasks
percona/proxysql-admin-tool-doc pull request #80
Opened 2023-02-09 16:27 UTC by alina-derkach-oaza

modified:   docs/release-notes.md
modified:   mkdocs-base.yml
new file:   docs/2.4.7.md

2023-02-13 05:47 UTC, venkatesh-prasad-v approved these changes

2023-02-13 06:29 UTC, mohitj1988 approved these changes

2023-02-14 11:14 UTC, venkatesh-prasad-v requested changes

2023-02-14 11:54 UTC, alina-derkach-oaza commented on docs/2.4.7.md
> +
Added

2023-02-14 12:01 UTC, merged